In [15]:
import numpy as onp
import jax.numpy as jnp
from jax import jit, grad
from jax.ops import index_update
from jax.lax import scan
from collections import defaultdict
from typing import NamedTuple, Callable, Dict
from scipy.optimize import minimize
from functools import partial
from tqdm import tqdm
import pandas as pd

In [10]:
a = onp.array([[1,2],[3,4]])
a = onp.asmatrix(a)

In [11]:
a

matrix([[1, 2],
        [3, 4]])

In [12]:
cov_a = a

In [7]:
matrix_a = jnp.zeros((2,2))

In [17]:
test = onp.concatenate((cov_a, matrix_a), axis = 1)

In [18]:
test

matrix([[1., 2., 0., 0.],
        [3., 4., 0., 0.]])

In [19]:
b = onp.array([[2,3],[4,5]])
b = onp.asmatrix(b)

In [21]:
test_two = onp.concatenate((matrix_a, b), axis= 1)

In [22]:
test_two

matrix([[0., 0., 2., 3.],
        [0., 0., 4., 5.]])

In [24]:
cov_full = onp.concatenate((test, test_two), axis = 0)

In [26]:
cov_full

matrix([[1., 2., 0., 0.],
        [3., 4., 0., 0.],
        [0., 0., 2., 3.],
        [0., 0., 4., 5.]])

In [31]:
-onp.linalg.inv(cov_full)

matrix([[ 2. , -1. , -0. , -0. ],
        [-1.5,  0.5, -0. , -0. ],
        [-0. , -0. ,  2.5, -1.5],
        [-0. , -0. , -2. ,  1. ]])

In [29]:
def Create_cov_mat(cov_a, cov_b):
  ID_mat = jnp.zeros((cov_a.shape[0], cov_a.shape[1]))
  mat_a = onp.concatenate((cov_a, ID_mat), axis = 1)
  mat_b = onp.concatenate((ID_mat, cov_b), axis = 1)
  cov_full = onp.concatenate((mat_a, mat_b), axis = 0)

  return cov_full

In [33]:
Create_cov_mat(cov_a, b)

matrix([[1., 2., 0., 0.],
        [3., 4., 0., 0.],
        [0., 0., 2., 3.],
        [0., 0., 4., 5.]])

In [37]:
jnp.array(0.)

DeviceArray(0., dtype=float32)